### ISSUE TITLE
The zh doc still in process?

### ISSUE THREAD

**Issue by awxiaoxian2020** [microsoft/TypeScript-Website-Localizations#154]

**Comment by awxiaoxian2020** [comment]
@Kingwl The doc didn't update for a long time.

**Comment by Kingwl** [comment]
Sorry. I don't have much time recently.
I'll take a quick review in this week.

**Comment by awxiaoxian2020** [comment]
> Sorry. I don't have much time recently. I'll take a quick review in this week.

I can understand it. I think we can merge these PRs first. Make it better later.
