### ISSUE TITLE
The Github CI should not exist in fork repo

### ISSUE THREAD

**Issue by awxiaoxian2020** [microsoft/TypeScript-Website-Localizations#156]
See https://github.com/SylviaZ89/TypeScript-Website-Localizations/pull/1 .

**Comment by awxiaoxian2020** [comment]
@orta PTAL :)

**Comment by orta** [comment]
I don't have write access anymore I'm afraid

**Comment by awxiaoxian2020** [comment]
> I don't have write access anymore I'm afraid

Ah... Who can solve it...

**Comment by awxiaoxian2020** [comment]
@weswigham Could you solve this problem?
