### ISSUE TITLE
Status of Documentation Translations

### ISSUE THREAD

**Issue by juliogarciape** [microsoft/TypeScript-Website-Localizations#231]
Hi there :wave: 

I noticed there hasn't been much recent activity in the repository, and I wanted to check if you're still open to contributions. Specifically, I would like to help by translating the documentation into Spanish.

Could you please confirm if you're currently accepting PRs for language translations?

**Comment by jakebailey** [comment]
Not presently: https://github.com/microsoft/TypeScript-Website/issues/2804
