### ISSUE TITLE
Some texts related with 'go-to-translated-ver button' should be fixed

### ISSUE THREAD

**Issue by jihoon-seo** [microsoft/TypeScript-Website-Localizations#62]
**This is a Bug Report**

I guess that this is related with React-intl.

**Problem:**
![TS-l10n](https://user-images.githubusercontent.com/46767780/112706661-12457c80-8ee9-11eb-9e0d-d8b7696ec8a3.png)

**Proposed Solution:**

**Files to Update:**

**Comment by orta** [comment]
Sure, those are in https://github.com/microsoft/TypeScript-Website-Localizations/tree/main/docs/typescriptlang

**Comment by jihoon-seo** [comment]
- Fixed by the PR #63.

![image](https://user-images.githubusercontent.com/46767780/148037128-f90290cc-014b-4b2d-a7bd-4229d852f1cf.png)
